server/apps/posts/urls.py
from django.urls import path
from apps.posts import views

app_name = 'posts'

urlpatterns = [    
    path('', views.main),
    path('posts/create', views.create, name='create'),
    path('posts/detail/<int:pk>', views.detail, name='detail'),
    path('posts/update/<int:pk>', views.update, name='update'),
    path('posts/delete/<int:pk>', views.delete, name='delete'),
]

server/config/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.posts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/apps/posts/models.py
from django.db import models

class User(models.Model):
  name = models.CharField(max_length=20)
  age = models.IntegerField(default=0)
  
  def __str__(self):
    return self.name

class Post(models.Model):
  title = models.CharField('제목', max_length= 20)
  content = models.CharField('내용', max_length=20, blank=True)
  region = models.CharField('지역', max_length=20, blank=True)
  user = models.ForeignKey(User, verbose_name='작성자', on_delete=models.CASCADE)  
  price = models.IntegerField('가격', default=1000)
  photo = models.ImageField(blank=True, upload_to='posts/%Y%m%d')
  created_date = models.DateTimeField('작성일', blank=True, auto_created=True, auto_now_add=True)
  updated_date = models.DateTimeField('수정일', blank=True, auto_created=True, auto_now=True)
    

server/apps/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
  class Meta:
    model= Post
    fields = ('__all__')

server/apps/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
  

def main(request):
  min_price = request.GET.get('min_price')
  max_price = request.GET.get('max_price')
  search_txt = request.GET.get('search_txt')  
  print(request.GET)
  try:
    if max_price == '':
      posts = Post.objects.all().filter(price__lte=min_price)
    else:
      posts = Post.objects.all().filter(price__gte=min_price, price__lte=max_price)
  except ValueError:
    posts = Post.objects.all()
    
  ctx = {
    'posts': posts,
  }
  return render(request, 'posts/post_list.html', context=ctx)


def create(request):
  if request.method == 'GET':
    form = PostForm()       
    ctx = {'form': form,           
           }
    
    return render(request, 'posts/post_create.html', context = ctx)    
  else:
    form = PostForm(request.POST, request.FILES)    
    if form.is_valid():
      form.save()
      
    return redirect('/')
  

def detail(request, pk):
  target_post = Post.objects.get(id = pk)
  ctx = {'post' : target_post,}
  return render(request, 'posts/post_detail.html', context=ctx)
  
  
def update(request, pk):
  if request.method == 'GET':
    post = Post.objects.get(id=pk)
    form = PostForm(instance=post)    
    ctx = {'form': form,          
           'pk': pk}  
    
    return render(request, 'posts/post_update.html', context=ctx)
  else:
    post = Post.objects.get(id=pk)
    form = PostForm(request.POST, request.FILES, instance=post)
    if form.is_valid():      
      form.save()
    return redirect(f'/posts/detail/{pk}', pk)
  
  
def delete(request, pk):
  post = Post.objects.get(id=pk)
  post.delete()
  return redirect('/')

server/templates/posts/base.html
{%load static%}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{%static 'posts/css/style.css'%}">  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  {%block head%}


  {% endblock %}
</head>
<body>
  <main>
    <a href="/" id='logo' style='text-decoration: none; color: green;'><h1>🫑 피망 마켓 🫑</h1></a>
    <hr>
    {%block content%}
      
    
    {%endblock%}
  </main>
  <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
</body>
</html>

server/templates/posts/post_create.html
{% extends 'posts/base.html' %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {%block head%}
    <title>post_create</title>
    <style>
      main {
        height: 100vh;
      }
    </style>
    {% endblock %}
  </head>
  <body>
    {%block content%}
    <form
      action="{% url 'posts:create'%}"
      method="post"
      enctype="multipart/form-data"
    >
      {%csrf_token%} {{form.as_p}}
      {{form2.as_p}}
      <button class="btn btn-success">등록하기</button>
    </form>
    {%endblock%}
  </body>
</html>

server/templates/posts/post_detail.html
{% extends 'posts/base.html' %} {%load static%}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block head %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
    <style>
      main {
        padding: 40px;
        height: 100%;
      }
      img {
        margin: 20px 0;
      }
    </style>
    {% endblock%}
  </head>
  <body>
    {% block content %}
    <h1 style="color: green; font-size: 40px">{{post.title}}</h1>
    {% if post.photo.url != '' %}
    <img src="{{post.photo.url}}" alt="제품 이미지" />
    {% else %}
    <img src="{% static 'posts/image/no_img.png' %}" alt="대체 텍스트" />
    {% endif %}
    <p>작성자: {{post.user.name}}</p>
    <p>나이: {{post.user}}</p>
    <p>지역: {{post.region}}</p>
    <p>가격: {{post.price}}</p>
    <h2 class="my-3">{{post.content}}</h2>
    <p>작성일: {{post.created_date}}</p>
    <p>수정일: {{post.updated_date}}</p>
    <p>이 작성자의 글</p>

    <hr />
    <a href="{% url 'posts:update' post.pk%}" class="btn btn-primary"
      >수정하기</a
    >
    <a href="{% url 'posts:delete' post.pk%}" class="btn btn-danger"
      >삭제하기</a
    >
    {% endblock content %}
  </body>
</html>

server/templates/posts/post_list.html
{% extends 'posts/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {%block head%}
    <title>피망 마켓</title>
  {%endblock%}
</head>
<body>
{%block content%}
  <div class="search-box">    
    <form action="/">      
      {% comment %} <input class = 'form-control' type="input" name="search_txt" placeholder="검색어를 입력하세요" /> {% endcomment %}
      <input class = 'form-control' type="text" name="min_price" placeholder="최소 가격" />
      <input class = 'form-control mx-2' type="text" name="max_price" placeholder="최대 가격" />
      <input class = 'btn btn-outline-success mx-2' type="submit" value="검색" />      
    </form>
    <a href="{% url 'posts:create' %}" class = 'btn btn-secondary'>글 생성하러 가기</a>
  </div>

  <div class="content-wrapper">
    <hr>
    {% for post in posts %}
    <div class="item">      
      {% if post.photo != null and post.photo.url != "" %}
        <img src="{{ post.photo.url }}" alt="대체 텍스트" />     
      {% else %}
        <img src="{% static 'posts/image/no_img.png' %}" alt="대체 텍스트" />     
      {% endif %}
      <div class="info">
        <a class="title" href="{% url 'posts:detail' post.pk %}"
          >{{post.title}}</a
        >
        <p class="region">지역: {{post.region}}</p>
        <p class="price">가격: {{post.price}}</p>
        <p class="create-date">작성일: {{post.created_date}}</p>
      </div>
    </div>
    <hr />
    {% endfor %}
  </div>
</main>
{%endblock%}
</body>
</html>

server/templates/posts/post_update.html
{% extends 'posts/base.html' %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {%block head %}
    <title>post_detail</title>
    <style>
      main {
        height: 100vh;
        padding: 40px;
      }
    </style>
    {%endblock%}
  </head>
  <body>
    {%block content%}
    <form
      action="{% url 'posts:update' pk%}"
      method="post"
      enctype="multipart/form-data"
    >
      {%csrf_token%} {{form.as_p}}
      <button class="btn btn-primary">수정 완료</button>
    </form>
    {%endblock%}
  </body>
</html>